daemonizing

diff --git a/iptrestd b/iptrestd
--- a/iptrestd
+++ b/iptrestd
@@ -1,50 +1,95 @@
-#!/usr/bin/env python
-# coding: utf-8
-import autorest.autorest as autorest
-import bottle
+#!/bin/bash
 
-IPTREST_APP='/opt/iptrest/iptrest'
+APP=/usr/bin/iptrestdaemon
+LOGS=/var/log/iptrest.log
+PIDFILE=/var/run/iptrest.pid
 
-functions = {
-    'redir': {
-        'route': '',
-        'callback': {
-            'type': 'application',
-            'command': [ IPTREST_APP, 'list', '-j' ]
-        }
-    },
-    'redir_put': {
-        'route': '',
-        'method': 'PUT',
-        'parameters': [ 's_port', 'ip', 'port' ],
-        'callback': {
-            'type': 'application',
-            'command': [ IPTREST_APP, 'add', '-s', '<s_port>', '-i', '<ip>', '-d', '<port>', '-pj' ]
-        }
-    },
-    'redir_del_port': {
-        'route': '',
-        'method': 'DELETE',
-        'parameters': [ 'port' ],
-        'callback': {
-            'type': 'application',
-            'command': [ IPTREST_APP, 'del', '-s', '<port>', '-pj' ]
-        }
-    },
-    'redir_del_ip': {
-        'route': '',
-        'method': 'DELETE',
-        'parameters': [ 'ip', 'port' ],
-        'callback': {
-            'type': 'application',
-            'command': [ IPTREST_APP, 'del', '-s', '<port>', '-i', '<ip>', '-pj' ]
-        }
-    },
-    '#config': {
-        
-    }
+function checkpidfile() {
+    local PID=
+    PID="$(cat $PIDFILE 2> /dev/null | head -n 1)"
+    if [ "$PID" != "" ]; then
+        if ps "$PID" 2> /dev/null > /dev/null; then
+            return 1
+        else
+            rm "$PIDFILE"
+        fi
+    fi
+    return 0
 }
 
-if __name__ == '__main__':
-    autorest.setup_routing(functions)
-    bottle.run(host='localhost', port=8080)
+function killprocess() {
+    local PID=
+    PID="$(cat $PIDFILE 2> /dev/null | head -n 1)"
+    if [ "$PID" != "" ]; then
+        kill "$PID"
+        sleep 1
+        if ps "$PID" 2> /dev/null > /dev/null; then
+            return 1
+        fi
+        rm "$PIDFILE" 2> /dev/null
+    fi
+    return 0
+}
+
+function start() {
+    if checkpidfile; then
+        $APP >> $LOGS 2>> $LOGS &
+        if [ $? -eq 0 ]; then
+            CHILD=$!
+            echo "$CHILD" > "$PIDFILE"
+            if [ $? -ne 0 ]; then
+                echo "could not write the pidfile"
+            fi
+            echo "daemon started"
+        else
+            echo "could not start the application"
+            return 1
+        fi
+    else
+        echo "daemon already running"
+        return 1
+    fi    
+}
+
+function status() {
+    if checkpidfile; then
+        echo "daemon not running"
+        return 1
+    else
+        echo "daemon running"
+        return 0
+    fi    
+}
+
+function stop() {
+    if checkpidfile; then
+        echo "daemon not running"
+        return 1
+    else
+        if killprocess; then
+            echo "daemon stopped"
+            return 0
+        else
+            echo "could not stop daemon"
+            return 2
+        fi
+    fi    
+}
+
+case $1 in
+    start)  start
+            exit $?
+            ;;
+    status) status
+            exit $?
+            ;;
+    stop)   stop
+            exit $?
+            ;;
+    restart)
+            stop
+            [ $? -gt 1 ] && exit 1
+            start
+            exit $?
+            ;;
+esac
